### ISSUE TITLE
Trabajo finalizado

### ISSUE THREAD

**Issue by irgarcia31** [irgarcia31/testsim#1]

**Comment by tdido** [comment]
@irgarcia31

**Comment by tdido** [comment]
@irgarcia31 según veo en el último commit 6b022adb4ea45b5afb59a53ec320a5bab71e0a8a, sólo está incluído el archivo de ambiente, pero falta el script (o las modificaciones).

**Comment by irgarcia31** [comment]
ya está subido el script, disculpa!

**Comment by tdido** [comment]
Muy bien, el pipeline funciona correctamente, buen trabajo. Te hago dos comentarios menores, pero cierro la incidencia porque el resultado es correcto.

Dos comentarios menores:
- En lugar de pegar el contenido del script "analyse_sample" dentro del nuevo script, lo ideal hubiera sido llamar a "analyse_sample" dentro del loop. Algo así:
```shell
for sampleid in $(ls data/*.fastq.gz | cut -d "_" -f1 | sed 's:data/::' | sort | uniq)
do
    bash scripts/analyse_sample.sh $sampleid
done
```
- No conviene llamar a software interactivo como firefox desde un pipeline, con lo cual el comando que abre el reporte de multiqc mejor dejarlo para que lo ejecute a mano quien mire los datos.
